import type { ServiceDocument } from '../models/Service';
import type { HairstyleDocument } from '../models/Hairstyle';
import type { ReviewDocument } from '../models/Review';
import type { FaqDocument } from '../models/Faq';

export const faqsSeed: Array<Partial<FaqDocument>> = [
  {
    question: 'How do I book an appointment?',
    answer:
      'Tap "BOOK NOW" anywhere on the site and pick your service, barber, date and time. You will see a confirmation screen instantly and we will call you to confirm.',
    sortOrder: 1,
    isActive: true,
  },
  {
    question: 'Can I walk in without a booking?',
    answer:
      'Yes, walk-ins are always welcome. Booking ahead simply means less waiting and a guaranteed slot at your preferred time.',
    sortOrder: 2,
    isActive: true,
  },
  {
    question: 'Do I need to pay online?',
    answer:
      'No. Booking is completely free and you only pay at the salon after your service.',
    sortOrder: 3,
    isActive: true,
  },
  {
    question: 'How do I know the haircut will suit me?',
    answer:
      'Tell us what you like and our barbers will suggest the best style for your face shape and hair type. If you are not sure, we will guide you.',
    sortOrder: 4,
    isActive: true,
  },
  {
    question: 'What if I need to cancel or reschedule?',
    answer:
      'Just call us or visit the salon and we will shift your booking to another slot that suits you. No charges, no hassle.',
    sortOrder: 5,
    isActive: true,
  },
  {
    question: 'Do you offer grooming for weddings and events?',
    answer:
      'Yes. We offer complete wedding grooming including haircut, beard styling, face cleanup and a royal finish. Contact us to plan it.',
    sortOrder: 6,
    isActive: true,
  },
];

export const servicesSeed: Array<Partial<ServiceDocument>> = [
  {
    tamilName: 'கம்பீரன்',
    englishName: 'Classic Haircut',
    subtitle: 'CLASSIC HAIRCUT',
    description:
      'உன் முகத்திற்கு ஏற்ற clean வெட்டு. எப்போதும் sharp-ஆ இருக்க கிளாசிக் cut + neck finish.',
    durationMinutes: 30,
    price: null,
    priceVisible: false,
    category: 'haircut',
    sortOrder: 1,
    isSignature: false,
    isActive: true,
  },
  {
    tamilName: 'தலைவன்',
    englishName: 'Premium Fade',
    subtitle: 'PREMIUM FADE',
    description:
      'Sharp fade, blend மற்றும் modern look — உன் அடையாளத்தை statement-ஆ கொண்டாடு.',
    durationMinutes: 40,
    price: null,
    priceVisible: false,
    category: 'haircut',
    sortOrder: 2,
    isSignature: true,
    isActive: true,
  },
  {
    tamilName: 'மீசைக்காரன்',
    englishName: 'Signature Beard',
    subtitle: 'SIGNATURE BEARD',
    description:
      'விஸ்கர்ஸ் முதல் ஷேப்பிங் வரை — முகத்திற்கு வலு சேர்க்கும் perfect beard styling.',
    durationMinutes: 25,
    price: null,
    priceVisible: false,
    category: 'beard',
    sortOrder: 3,
    isSignature: true,
    isActive: true,
  },
  {
    tamilName: 'நாயகன்',
    englishName: 'Hair + Beard Combo',
    subtitle: 'HAIR + BEARD COMBO',
    description:
      'முழுமையான மாற்றம் — hair cut + beard + finish, நேரத்தையும் பணத்தையும் சேமி.',
    durationMinutes: 60,
    price: null,
    priceVisible: false,
    category: 'combo',
    sortOrder: 4,
    isSignature: true,
    isActive: true,
  },
  {
    tamilName: 'முகம்',
    englishName: 'Face Cleanup',
    subtitle: 'FACE CLEANUP',
    description:
      'தோல் சுத்தம் + soothing scrub. ஸ்டைலுக்கு முன் சுத்தமான முகம்.',
    durationMinutes: 20,
    price: null,
    priceVisible: false,
    category: 'facial',
    sortOrder: 5,
    isSignature: false,
    isActive: true,
  },
  {
    tamilName: 'இளைப்பாறல்',
    englishName: 'Head Massage',
    subtitle: 'HEAD MASSAGE',
    description:
      'வாரம் முழுவதும் களைத்த மனதிற்கு ரிலாக்ஸ். தலை மசாஜ் + shoulder relax.',
    durationMinutes: 15,
    price: null,
    priceVisible: false,
    category: 'spa',
    sortOrder: 6,
    isSignature: false,
    isActive: true,
  },
  {
    tamilName: 'திருப்பம்',
    englishName: 'Textured Crop',
    subtitle: 'TEXTURED CROP',
    description:
      'இளைய தலைமுறை love செய்யும் textured crop — easy styling, trendy look.',
    durationMinutes: 35,
    price: null,
    priceVisible: false,
    category: 'haircut',
    sortOrder: 7,
    isSignature: false,
    isActive: true,
  },
  {
    tamilName: 'பளிச்சென்ற மொட்டை',
    englishName: 'Bald / Skin Fade',
    subtitle: 'BALD & SKIN FADE',
    description:
      'Confident bald look அல்லது sharp skin fade — கண்டம் மறைக்காத அழகு.',
    durationMinutes: 25,
    price: null,
    priceVisible: false,
    category: 'haircut',
    sortOrder: 8,
    isSignature: false,
    isActive: true,
  },
];

export const hairstylesSeed: Array<Partial<HairstyleDocument>> = [
  {
    tamilName: 'கிளாசிக் சைட் பார்ட்',
    englishName: 'Classic Side Part',
    category: 'classic',
    description: 'காலத்தால் அழியாத clean side part — professional & திடமான தோற்றம்.',
    faceShapes: ['oval', 'rectangle', 'diamond'],
    styleTypes: ['professional', 'classic', 'low-maintenance'],
    hairTypes: ['straight', 'wavy'],
    sortOrder: 1,
    isActive: true,
  },
  {
    tamilName: 'லோ ஃபேட்',
    englishName: 'Low Fade',
    category: 'fade',
    description: 'மென்மையான fade, எந்த முகவடிவத்திற்கும் suit — subtle & clean.',
    faceShapes: ['oval', 'round', 'square'],
    styleTypes: ['modern', 'low-maintenance'],
    hairTypes: ['straight', 'wavy', 'curly'],
    sortOrder: 2,
    isActive: true,
  },
  {
    tamilName: 'ஹை ஃபேட்',
    englishName: 'High Fade',
    category: 'fade',
    description: 'Bold high fade — சட்டென்று attention இழுக்கும் young attitude.',
    faceShapes: ['oval', 'diamond'],
    styleTypes: ['bold', 'modern'],
    hairTypes: ['straight', 'wavy'],
    sortOrder: 3,
    isActive: true,
  },
  {
    tamilName: 'டெக்ஸ்சர்டு கிராப்',
    englishName: 'Textured Crop',
    category: 'textured',
    description: 'நேர்த்தியான texture + fringe — comfortable and stylish.',
    faceShapes: ['oval', 'square', 'heart'],
    styleTypes: ['modern', 'low-maintenance'],
    hairTypes: ['straight', 'wavy', 'curly'],
    sortOrder: 4,
    isActive: true,
  },
  {
    tamilName: 'ஸ்லிக் பேக்',
    englishName: 'Slick Back',
    category: 'formal',
    description: 'மூன்று நிமிடத்தில் டஃப் audience-க்கு மாறும் executive style.',
    faceShapes: ['oval', 'rectangle'],
    styleTypes: ['professional', 'classic'],
    hairTypes: ['straight', 'wavy'],
    sortOrder: 5,
    isActive: true,
  },
  {
    tamilName: 'குர்லி டாப்',
    englishName: 'Curly Top',
    category: 'modern',
    description: 'உன் இயற்கையான curls-ஐ பவர்ஃபுல்-ஆக காட்டும் style.',
    faceShapes: ['round', 'square', 'oval'],
    styleTypes: ['modern', 'bold'],
    hairTypes: ['curly'],
    sortOrder: 6,
    isActive: true,
  },
  {
    tamilName: 'க்ரூ கட்',
    englishName: 'Crew Cut',
    category: 'classic',
    description: 'Military sharp crew cut — கனமான, நேர்த்தியான masculine look.',
    faceShapes: ['oval', 'rectangle', 'diamond'],
    styleTypes: ['professional', 'low-maintenance', 'classic'],
    hairTypes: ['straight', 'wavy', 'curly'],
    sortOrder: 7,
    isActive: true,
  },
  {
    tamilName: 'பம்ப் & டேப்பர்',
    englishName: 'Bump & Taper',
    category: 'modern',
    description: 'Modern bump styling + sharp taper — urban fresh look.',
    faceShapes: ['oval', 'heart'],
    styleTypes: ['modern', 'bold'],
    hairTypes: ['straight', 'wavy'],
    sortOrder: 8,
    isActive: true,
  },
  {
    tamilName: 'கம்பீர தாடி',
    englishName: 'Signature Beard',
    category: 'beard',
    description: 'Sharp lining + shape — தாடியில் full confidence.',
    faceShapes: ['oval', 'square', 'rectangle'],
    styleTypes: ['professional', 'bold'],
    hairTypes: ['straight', 'wavy', 'curly'],
    sortOrder: 9,
    isActive: true,
  },
  {
    tamilName: 'ஸ்டபிள் பியர்டு',
    englishName: 'Stubble Beard',
    category: 'beard',
    description: 'Low-maintenance stubble — நாட்கள் தோறும் நேர்த்தியாக இருக்க.',
    faceShapes: ['round', 'oval', 'heart'],
    styleTypes: ['modern', 'low-maintenance'],
    hairTypes: ['straight', 'wavy', 'curly'],
    sortOrder: 10,
    isActive: true,
  },
  {
    tamilName: 'மாபெரும் மாற்றம்',
    englishName: 'Hair + Beard Combo',
    category: 'hair-beard',
    description: 'உள்ளே நுழைந்தால் நேர்த்தி, வெளியே சென்றால் royalty — முழு மேக்கோவர்.',
    faceShapes: ['oval', 'square', 'rectangle'],
    styleTypes: ['professional', 'bold', 'modern'],
    hairTypes: ['straight', 'wavy', 'curly'],
    sortOrder: 11,
    isActive: true,
  },
];

export const reviewsSeed: Array<Partial<ReviewDocument>> = [
  {
    name: 'Murugan',
    initial: 'M',
    rating: 5,
    text: 'மிகவும் அக்கறையுடன் ஸ்டைல் பண்ணுவாங்க. நான் எதிர்பார்த்ததை விட நல்லா வந்தது. முகத்தோட ஒத்து போற haircut குடுக்கறதுல இவங்க லெவலுக்கு யாருமில்ல.',
    service: 'Premium Fade',
    sortOrder: 5,
    isActive: true,
  },
  {
    name: 'Arun',
    initial: 'A',
    rating: 5,
    text: '23 வருஷ அனுபவம் வெளிச்சமா தெரியுது. ஹேர்கட் மட்டுமில்ல, உனக்கு எந்த ஸ்டைல் நல்லா இருக்குமுன்னு guide செஞ்சாங்க. அருமையான experience.',
    service: 'Classic Haircut',
    sortOrder: 4,
    isActive: true,
  },
  {
    name: 'Saravanan',
    initial: 'S',
    rating: 4,
    text: 'ரொம்ப நேர்த்தியா வெட்டுவாங்க. மீசை கத்தரி work சூப்பர். டைம்-க்கு கிளினிக்கா போனா waiting கம்மி.',
    service: 'Signature Beard',
    sortOrder: 3,
    isActive: true,
  },
  {
    name: 'Karthik',
    initial: 'K',
    rating: 5,
    text: 'ஃபேட் ஸ்டைல்ல எனக்கு ரொம்ப பிடிச்சது. ஃபோன்ல appointment எடுக்கறது easy. Driver-க்கு கியர் மாதிரி நமக்கு ஸ்டைல் குடுக்கறாங்க!',
    service: 'Premium Fade',
    sortOrder: 2,
    isActive: true,
  },
  {
    name: 'Vignesh',
    initial: 'V',
    rating: 5,
    text: 'முதல்ல ரொம்ப பொடியா பயந்து வந்தேன். ஆனா அவங்க சொன்ன ஸ்டைல் எனக்கு ரொம்ப அழகா இருந்தது. இனிமே இங்கதான். அன்பான ஆட்கள்.',
    service: 'Hair + Beard Combo',
    sortOrder: 1,
    isActive: true,
  },
];