import fs from 'fs';
import path from 'path';
import type { Request, Response } from 'express';
import { asyncHandler } from '../utils/asyncHandler';
import { ok } from '../utils/apiResponse';
import { ApiError } from '../utils/ApiError';
import { storeUploadedMedia } from '../services/mediaService';
import { deleteMedia } from '../services/fileStorage';

/**
 * POST /api/admin/media/upload
 * Uploads an image or video file and returns a web-accessible URL + publicId.
 * The record that references it is saved separately (upload-then-attach),
 * which keeps storage concerns out of the per-resource controllers.
 */
export const uploadMediaHandler = asyncHandler(async (req: Request, res: Response) => {
  if (!req.file) throw ApiError.badRequest('A media file is required', 'FILE_REQUIRED');
  const media = await storeUploadedMedia(req.file);
  ok(
    res,
    {
      url: media.url,
      publicId: media.publicId,
      mediaType: media.mediaType,
      sourceType: media.sourceType,
      size: req.file.size,
      originalName: req.file.originalname,
    },
    'Media uploaded',
    201,
  );
});

/**
 * GET /api/admin/media/local
 * Lists images/videos stored inside the frontend public directory so the
 * admin can reuse existing local media without typing paths manually.
 */
export const listLocalMediaHandler = asyncHandler(async (_req: Request, res: Response) => {
  const base = path.resolve(process.cwd(), '../frontend/public');
  const roots: { dir: string; urlPrefix: string; mediaType: 'image' | 'video' }[] = [
    { dir: path.join(base, 'images'), urlPrefix: '/images', mediaType: 'image' },
    { dir: path.join(base, 'videos'), urlPrefix: '/videos', mediaType: 'video' },
  ];

  const files: { path: string; name: string; mediaType: 'image' | 'video'; size: number }[] = [];
  for (const root of roots) {
    if (!fs.existsSync(root.dir)) continue;
    const walk = (current: string): void => {
      for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
        if (entry.name.startsWith('.')) continue;
        const full = path.join(current, entry.name);
        if (entry.isDirectory()) {
          walk(full);
        } else if (entry.isFile()) {
          const rel = path.relative(root.dir, full).split(path.sep).join('/');
          const stat = fs.statSync(full);
          files.push({
            path: `${root.urlPrefix}/${rel}`,
            name: entry.name,
            mediaType: root.mediaType,
            size: stat.size,
          });
        }
      }
    };
    walk(root.dir);
  }

  files.sort((a, b) => a.path.localeCompare(b.path));
  ok(res, files);
});

const SAFE_UPLOAD_NAME = /^(media|upload)-\d+-\d+\.(jpg|jpeg|png|webp|mp4|webm|mov)$/i;

/**
 * DELETE /api/admin/media/:publicId
 * Removes an uploaded media file from application storage. Only filenames
 * generated by this application are eligible — external URLs are never touched.
 */
export const deleteMediaFileHandler = asyncHandler(async (req: Request, res: Response) => {
  const publicId = req.params.publicId;
  if (!publicId) throw ApiError.badRequest('publicId is required', 'BAD_REQUEST');

  const mediaType = req.query.mediaType === 'video' ? 'video' : 'image';
  const basename = path.basename(publicId);
  if (!SAFE_UPLOAD_NAME.test(basename)) {
    throw ApiError.badRequest('Not an application-owned media file', 'INVALID_MEDIA_ID');
  }
  await deleteMedia(basename, mediaType);
  ok(res, null, 'Media file removed');
});